name: Make manylinux wheels 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [manylinux1_x86_64, manylinux2010_x86_64]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run build-wheels script
        uses: docker://quay.io/pypa/${{ matrix.platform }}  
        with:
          args: >-
            -e PLAT=${{ matrix.platform}} 
            -v `pwd`:$GITHUB_WORKSPACE
            $GITHUB_WORKSPACE/.github/workflows/build-wheels.sh
